#!/usr/bin/env bash
# Materialize the SEKAR staging runtime env at /opt/sekar/.env.
#
# With dotenvx, the bulk of the backend config now lives in the committed, ENCRYPTED
# be/.env.staging baked into the image. The only thing the container needs at runtime
# is the private key to decrypt it. So this file contains just that key (pulled from
# SSM Parameter Store via the EC2 instance role). NODE_ENV + REDIS_URL are set by
# compose.staging.yml. See specs/deployment/encrypted-secrets.md.
#
#   bash infra/seed-env-from-ssm.sh
set -euo pipefail

REGION="${AWS_REGION:-ap-southeast-3}"
OUT=/opt/sekar/.env

get() {
  aws ssm get-parameter --region "$REGION" --name "$1" --with-decryption \
    --query Parameter.Value --output text
}

# Storage name is BE_DOTENV_PRIVATE_KEY (consistent with WEB_/MOBILE_); the runtime
# var dotenvx needs is DOTENV_PRIVATE_KEY_STAGING (derived from the .env.staging filename).
DOTENV_PRIVATE_KEY_STAGING="$(get /sekar/staging/BE_DOTENV_PRIVATE_KEY)"

# /opt/sekar must be owned by the user that runs `docker compose` (ec2-user) so the
# compose `env_file:` can be read — the Docker CLI reads it as the invoking user.
sudo mkdir -p /opt/sekar
sudo chown -R "$(id -un)":"$(id -gn)" /opt/sekar
umask 077
cat > "$OUT" <<EOF
# Generated by infra/seed-env-from-ssm.sh — do not edit by hand.
# Single dotenvx private key; everything else is in the encrypted be/.env.staging
# baked into the backend image and decrypted at boot by load-env.ts.
DOTENV_PRIVATE_KEY_STAGING=${DOTENV_PRIVATE_KEY_STAGING}
EOF

sudo chmod 600 "$OUT"
echo "Wrote $OUT (dotenvx private key only)"
