#!/usr/bin/env bash
# Materialize the SEKAR staging runtime env at /opt/sekar/.env.
#
# Secrets are pulled from SSM Parameter Store (SecureString, decrypted via the EC2
# instance role); everything else is non-secret static config. Run on the box at
# deploy time, before `docker compose -f compose.staging.yml up`.
#
#   bash infra/seed-env-from-ssm.sh
set -euo pipefail

REGION="${AWS_REGION:-ap-southeast-3}"
OUT=/opt/sekar/.env
RDS_HOST="${RDS_HOST:-kobin-kpi-db.cvuoeguwo5dg.ap-southeast-3.rds.amazonaws.com}"

get() {
  aws ssm get-parameter --region "$REGION" --name "$1" --with-decryption \
    --query Parameter.Value --output text
}

DB_PASS="$(get /sekar/staging/DATABASE_PASSWORD)"
JWT="$(get /sekar/staging/JWT_SECRET)"
JWT_R="$(get /sekar/staging/JWT_REFRESH_SECRET)"

# /opt/sekar must be owned by the user that runs `docker compose` (ec2-user) so the
# compose `env_file:` can be read — the Docker CLI reads it as the invoking user.
sudo mkdir -p /opt/sekar
sudo chown -R "$(id -un)":"$(id -gn)" /opt/sekar
umask 077
cat > "$OUT" <<EOF
# Generated by infra/seed-env-from-ssm.sh — do not edit by hand. Secrets from SSM.
NODE_ENV=staging
PORT=3000

# Database (AWS RDS — shared instance, dedicated db/role)
DATABASE_HOST=${RDS_HOST}
DATABASE_PORT=5432
DATABASE_USER=sekar
DATABASE_PASSWORD=${DB_PASS}
DATABASE_NAME=sekar_staging
DATABASE_SSL=true
DATABASE_SYNCHRONIZE=false
DATABASE_MIGRATIONS_RUN=false

# Auth
JWT_SECRET=${JWT}
JWT_REFRESH_SECRET=${JWT_R}
JWT_EXPIRATION=15m
JWT_ACCESS_EXPIRATION=15m
JWT_REFRESH_EXPIRATION=7d

# Object storage — real AWS S3 via the EC2 instance role (NO static keys)
AWS_REGION=ap-southeast-3
AWS_S3_BUCKET=sekar-media-staging

# Redis (in-stack container; overridden to the service name by compose)
REDIS_URL=redis://redis:6379
BULLMQ_PREFIX=sekar-staging

# CORS — the public web origin (HTTP for UAT; no TLS terminated yet)
CORS_ORIGIN=http://sekar.wahyutrip.com

# Push notifications disabled until Firebase is configured for staging
FCM_ENABLED=false

# Observability
SENTRY_ENVIRONMENT=staging

# Rate limiting (prod-safe defaults)
THROTTLE_TTL=60000
THROTTLE_LIMIT=100
AUTH_LOGIN_THROTTLE_LIMIT=5
AUTH_LOGIN_THROTTLE_TTL=60000
EOF

sudo chmod 600 "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
