/**
 * Generates the Android cold-start splash artwork: the SEKAR box lockup + "SEKAR"
 * wordmark + tagline, baked into drawable-{dpi}/splash_logo.png at every density. Text
 * uses the bundled brand fonts (Space Grotesk / Inter) via a temp fontconfig.
 *
 *   node scripts/generate-splash.mjs
 *
 * (iOS shows the tagline as native storyboard labels; the box-only imageset for the
 *  iOS launch + the app icons are generated by scripts/generate-app-icon.mjs.)
 */
import { mkdirSync } from 'node:fs';
import * as fs from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const FONTS = join(ROOT, 'assets/fonts');

// fontconfig MUST be configured before libvips (sharp) initializes — set it, write
// the config, then dynamic-import sharp.
const FC = '/tmp/sekar-fontconfig';
fs.mkdirSync(FC, { recursive: true });
fs.writeFileSync(
  join(FC, 'fonts.conf'),
  `<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd"><fontconfig><dir>${FONTS}</dir><cachedir>${FC}/cache</cachedir></fontconfig>`,
);
process.env.FONTCONFIG_FILE = join(FC, 'fonts.conf');
const sharp = (await import('sharp')).default;

// ─── Brand tokens ─────────────────────────────────────────────────────────────
const BLADE = 'M 0 -14 Q 18 -38 0 -42 Q -14 -38 0 -14 Z';
const ANGLES = [0, 45, 90, 135, 180, 225, 270, 315];
const SAGE = '#7FBC8C';
const CENTER = '#FDFD96';
const INK = '#1C1917';
const TAGLINE_GRAY = '#57534E';

const blades = ANGLES.map(
  (a) => `<g transform="rotate(${a})"><path d="${BLADE}" fill="${SAGE}" stroke="${INK}" stroke-width="3" stroke-linejoin="round"/></g>`,
).join('');

// Tilted white NB-box lockup inside a 0..120 region (matches SekarLogoBox / app icon).
const lockup = () => {
  const box = 84;
  const x = 60 - box / 2;
  const off = +(box * 0.075).toFixed(2);
  const rx = +(box * 0.2).toFixed(2);
  const bw = +(box * 0.06).toFixed(2);
  const pw = ((box * 0.6) / 84).toFixed(3);
  return (
    `<g transform="rotate(-6 60 60)">` +
    `<rect x="${x + off}" y="${x + off}" width="${box}" height="${box}" rx="${rx}" fill="${INK}"/>` +
    `<rect x="${x}" y="${x}" width="${box}" height="${box}" rx="${rx}" fill="#FFFFFF" stroke="${INK}" stroke-width="${bw}"/>` +
    `<g transform="translate(60 60) scale(${pw})">${blades}<circle r="12" fill="${CENTER}" stroke="${INK}" stroke-width="3"/></g>` +
    `</g>`
  );
};

// 320×236 dp artwork: lockup (top) + SEKAR + tagline. Transparent so the sage
// layer-list canvas shows through.
const W = 320;
const H = 236;
const splashSvg = (scale) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${W * scale}" height="${H * scale}" viewBox="0 0 ${W} ${H}">` +
  `<g transform="translate(100 8)">${lockup()}</g>` +
  `<text x="160" y="176" text-anchor="middle" font-family="Space Grotesk" font-weight="700" font-size="40" letter-spacing="-1" fill="${INK}">SEKAR</text>` +
  `<text x="160" y="204" text-anchor="middle" font-family="Inter" font-weight="500" font-size="12.5" letter-spacing="2" fill="${TAGLINE_GRAY}">SISTEM EVALUASI KINERJA SATGAS RTH</text>` +
  `</svg>`;

const RES = join(ROOT, 'android/app/src/main/res');
const DENSITY = { 'drawable-mdpi': 1, 'drawable-hdpi': 1.5, 'drawable-xhdpi': 2, 'drawable-xxhdpi': 3, 'drawable-xxxhdpi': 4 };

console.log('Android splash artwork (logo + SEKAR + tagline):');
for (const [dir, scale] of Object.entries(DENSITY)) {
  const out = join(RES, dir, 'splash_logo.png');
  mkdirSync(dirname(out), { recursive: true });
  await sharp(Buffer.from(splashSvg(scale))).png().toFile(out);
  console.log('  ✓', out.replace(ROOT + '/', ''), `(${Math.round(W * scale)}×${Math.round(H * scale)})`);
}
console.log('Done.');
